spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: Watermelon@1
stripe:
  apiURL: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP

payment-gateway: stripe

server:
  port: 8080
  servlet:
   context-path: /api/v1