spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: Watermelon@1
  flyway:
    repair-on-migrate: true
    out-of-order: true
  jpa:
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /api/v1
